### ISSUE TITLE
charred should be tried before data.json

### ISSUE THREAD

**Issue by borkdude** [babashka/json#2]
@lispyclouds charred should be tried before data.json since this library has a dependency on data.json for convenience, it will always win

https://github.com/babashka/json/blob/1d91f3ba62c50e1966e9dfd3c52519cc7d312fbb/src/babashka/json.clj#L13

**Comment by lispyclouds** [comment]
ah, doing another PR.

**Comment by lispyclouds** [comment]
Fixed in https://github.com/babashka/json/commit/99e984bf9dcf4f35b4d0911807e792b90213e9dc
